### ISSUE TITLE
Does not work with webpack 4

### ISSUE THREAD

**Issue by lifeiscontent** [softwareventures/resolve-typescript-plugin#18]
would like to use this plugin in storybook, I've got a local version of this plugin working with storybook + webpack 5, but when using webpack 4, it fails to compile.

**Comment by djcsdy** [comment]
Thanks for reporting, I'll take a look.

**Comment by djcsdy** [comment]
https://github.com/storybookjs/storybook/pull/15973

**Comment by lifeiscontent** [comment]
@djcsdy any updates here?

**Comment by djcsdy** [comment]
@lifeiscontent It's on my todo list but none of my clients need this, and paid work takes priority. Hope you understand :-).

**Comment by ascott18** [comment]
It seems to work fine for me, with the exception that I have to install it with `--force` due to the peer dependency requiring webpack 5.

**Comment by djcsdy** [comment]
I added some automated tests to verify that resolve-typescript plugin works with webpack 4.x and it does indeed seem to work as expected.

Therefore, as of version 1.2, resolve-typescript-plugin officially supports webpack 4.x as well as 5.x.

@lifeiscontent I think the problems you are seeing must be an incompatibility with either some specific configuration option, or some plugin you are using in conjunction with webpack. If you can identify what the problem is and there's something I can do to fix it then I'm happy to do so, but I don't have the bandwidth to investigate that myself.
