### ISSUE TITLE
Provide a ESM export?

### ISSUE THREAD

**Issue by Cobertos** [softwareventures/resolve-typescript-plugin#27]
When using this plugin inside of a `webpack.config.ts` I have to do something along the lines of

```typescript
import _ResolveTypeScriptPlugin from 'resolve-typescript-plugin';
// @ts-ignore
const ResolveTypeScriptPlugin = _ResolveTypeScriptPlugin.default;
```

as doing both

`import ResolveTypeScriptPlugin from 'resolve-typescript-plugin';` and
`import * as ResolveTypeScriptPlugin from 'resolve-typescript-plugin';` result in

```console
[webpack-cli] Failed to load '/home/cobertos/Seafile/projects/mapcast/monorepo/pkg/app-auctions/webpack.config.ts' config
[webpack-cli] webpack.config.ts:85:19 - error TS2351: This expression is not constructable.
  Type 'typeof import("/home/cobertos/Seafile/projects/mapcast/monorepo/node_modules/resolve-typescript-plugin/index")' has no construct signatures.

85     plugins: [new ResolveTypeScriptPlugin()]
                     ~~~~~~~~~~~~~~~~~~~~~~~

```

I think this is because the built `index.js` is using?

```javascript
Object.defineProperty(exports, "__esModule", { value: true });
//...
exports.default = ResolveTypescriptPlugin;
```

instead of commonjs `module.exports` or ESM `export default ...`.

**Comment by djcsdy** [comment]
The error you're seeing is coming from TypeScript. The error is happening during type checking, not at runtime. So it's not caused by anything in this project's `index.js`, since TypeScript won't even look at that. If anything is wrong with this project, it's the `index.d.ts`, which is the file TypeScript uses for type checking. But the `index.js` and `index.d.ts` that we distribute are untouched output from the TypeScript compiler, so they should work as-is. I have a bunch of other projects using this exact configuration and they're able to be imported from TypeScript projects just fine.

node has some built-in magic to allow importing CommonJS modules as if they're ESM modules. This is intended to smooth over the transition from CommonJS to ESM until ESM is used everywhere. The lines you're quoting from `index.js` should be enough to tell node that an ESM import-default should resolve to the exported `default` value. `exports` is the same as `module.exports` in CommonJS.

So, `import ResolveTypeScriptPlugin from 'resolve-typescript-plugin';` should work as is.

If it doesn't I suspect:
 * Something is set up incorrectly in your project.
 * webpack's integration with TypeScript somehow handles types incorrectly when importing CommonJS from an ESM module.

I have noticed that webpack tends to be a bit dodgy when writing config files in TypeScript and/or using ESM syntax in the past, so I've tended to stick to plain JS CommonJS config files myself even though I'm using TypeScript and ESM everywhere else.

As a test, please try importing and using the plugin from a plain JavaScript ESM module (no TypeScript). If that works then the problem is either with your config or with webpack.

If it still doesn't work then let me know and I'll look into it.

**Comment by djcsdy** [comment]
Actually, scratch that, you're right, this is not working as expected.

**Comment by djcsdy** [comment]
In the meantime you can work around this by writing your webpack.config in plain JS CommonJS. Which sucks, I know, but at least it works.

**Comment by otakustay** [comment]
According to https://github.com/microsoft/TypeScript/issues/47332, if we publish this package as a CJS package, we should use `export =` instead of `export default` to make sure it is fully interoperable with Node's native ESM, however this stops us from exporting types

A simpler fix is to just use named export instead of default export, I didn't find a solution to make TypeScript compile into `module.exports` but also able to export some types from `index.ts`, using named exports is a breaking change.

**Comment by djcsdy** [comment]
@Cobertos @otakustay Please test resolve-typescript-plugin v1.1.2-alpha.1 and let me know if it solves your problems.

You can install it using `npm i --save-dev resolve-typescript-plugin@alpha` or `yarn add resolve-typescript-plugin@alpha`.

**Comment by Cobertos** [comment]
Works for me!

![image](https://user-images.githubusercontent.com/6759176/149658701-60d03cdf-f1c0-4e54-b291-6407dedc5423.png)
![image](https://user-images.githubusercontent.com/6759176/149658752-31c2c125-584d-4a10-9bd3-7d9c7cde6c6d.png)


imports perfectly and is constructable without error :D :tada: 
Thanks youuu

**Comment by otakustay** [comment]
Having an error on `typescript@4.6.0-dev.20220114` with `"moduleResolution": "nodenext"`:

```
9 import ResolveTypeScriptPlugin from 'resolve-typescript-plugin';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in /Users/otakustay/Develop/reskript/packages/config-webpack/src/partials/base.ts:9
```

The `nodenext` module resolution won't automatically use `index.d.ts` as an entry, we need to put `"types": "./index.d.ts"` explicitly in `package.json`, I've manually added this to `node_modules/resolve-typescript-plugin/package.json` and everything works fine

**Comment by djcsdy** [comment]
Thanks @otakustay @Cobertos.

@otakustay I'm going to reopen #26 because clearly it is a separate issue and will push a fix later today.

**Comment by djcsdy** [comment]
I've done some testing and this doesn't seem to cause back-compat problems so expect it in the main release branch later today or tomorrow.
